### ISSUE TITLE
Redundant with `xorg-libpthread-stubs`

### ISSUE THREAD

**Issue by pkgw** [conda-forge/pthread-stubs-feedstock#3] opened 2017-01-28 21:03 UTC
Whoops. While working on providing the whole set of X.org client libraries with conda-forge, I didn't manage to discover that this package had already been created. The relatively new `xorg-libpthread-stubs` package is redundant with this one.

I'm biased but I'd recommend keeping `xorg-libpthread-stubs` and deprecating this one. That package is built on all three platforms, whereas this one is provided for Linux only. It also has a recipe and build scripts that are consistent with the rest of the X.org packages I've been working on.

I *think* this package is only used as a dependency of the Qt 5 package ... does anyone know if that's correct or not?

**Comment by ccordoba12** [comment] 2017-01-28 21:26
That's correct. I don't have a problem with deprecating this package since you're in charge of it now.

@ocefpaf, @jakirkham, what do you say?

**Comment by mingwandroid** [comment] 2017-01-28 21:52
My opinion is that we are trying to get towards increased binary compatibility and renaming packages works in the opposite direction.

**Comment by ccordoba12** [comment] 2017-01-28 21:57
Compatibility between conda-forge and defaults you mean?

**Comment by mingwandroid** [comment] 2017-01-28 22:04
Myself and @ocefpaf have spoke of trying to make things more compatible when possible. Qt5 from defaults was rebuilt with more recent jpeng and libpng libraries built by @ilanschnell. ICU is next on the list. If the concensus is that defaults needs to rename libxcb then so be it but in general I think new builds should try not to rename things without good reason.

**Comment by ccordoba12** [comment] 2017-01-28 22:19
I see, then @pkgw I'm -1 on removing this feedstock.

**Comment by ocefpaf** [comment] 2017-01-28 22:20
Ray, I agree. Let us take the shortest path towards compatibility. What side has fewer packages to fix? I  believe it is conda-forge, if so let's keep defaults' names.

I am not familiar with the packages in question. But I'll try to put a list together so we ca discuss this and reach a consensus to move forward.

**Comment by ocefpaf** [comment] 2017-01-28 22:22
BTW this was my mistake for not paying attention when reviewing and merging Peter's PRs. Sorry Peter.

**Comment by pkgw** [comment] 2017-01-28 22:34
It wouldn't be hard to switch things to remove the "xorg-" prefix from the packages that have already been added to conda-forge. I guess I'd like to keep the prefix for packages not already in defaults, but I don't feel especially strongly about that.

**Comment by mingwandroid** [comment] 2017-01-28 22:40
I like the prefix for ones that are not already there and conda is learning about deprecation too so if we keep the unprefixed ones for now, hopefully down the line we can deprecate them.

**Comment by ccordoba12** [comment] 2017-01-28 22:43
@pkgw, so what's the plan now? Remove the packages you added?

**Comment by pkgw** [comment] 2017-01-28 22:49
I guess the thing to do would be (1) import my build scripts as PRs to the existing packages, since they add support for more platforms, etc.; (2) apply the rename in dependent packages; (3) remove the `xorg-` prefixed packages.

**Comment by ccordoba12** [comment] 2017-01-28 22:54
Good plan! please go ahead with it then.

I'm closing this one as the issue is solved now.

**Closed as completed by ccordoba12** 2017-01-28 22:54 UTC
